name: Release

on:
  push:
    tags: ["v*.*.*"]

jobs:
  release:
    name: Create Release
    runs-on: macos-15
    env:
      DEVELOPER_DIR: "/Applications/Xcode_16.3.app/Contents/Developer"
    permissions:
      contents: write
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: swift build

      - name: Test
        run: swift test

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
